["fileversion","13.0.343","pointcount",8,"vertexcount",24,"primitivecount",6,"info",
    {
	"artist":"vangogh",
	"primcount_summary":"          6 Polygons\n",
	"hostname":"zundert",
	"bounds":[-0.5,0.5,-0.5,0.5,-0.5,0.5
	],
	"attribute_summary":"     1 point attributes:\tP\n",
	"date":"2014-09-09 09:27:54",
	"group_summary":"     1 primitive groups:\t\tfaces\n",
	"software":"Houdini 13.0.343"
    },"topology",
    ["pointref",
	["indices",
	    [1,5,4,0,2,6,5,1,3,7,6,2,0,4,7,3,2,1,0,3,5,6,7,4
	    ]
	]
    ],"attributes",
    ["vertexattributes",
	[
	],"pointattributes",
	[
	    [
		["scope","public","type","numeric","name","P","options",
		    {
			"type":{
			    "type":"string",
			    "value":"hpoint"
			}
		    }
		],
		["size",4,"storage","fpreal32","defaults",
		    ["size",4,"storage","fpreal64","values",
			[0,0,0,1
			]
		    ],"values",
		    ["size",4,"storage","fpreal32","tuples",
			[
			    [-0.5,-0.5,-0.5,1
			    ],
			    [0.5,-0.5,-0.5,1
			    ],
			    [0.5,-0.5,0.5,1
			    ],
			    [-0.5,-0.5,0.5,1
			    ],
			    [-0.5,0.5,-0.5,1
			    ],
			    [0.5,0.5,-0.5,1
			    ],
			    [0.5,0.5,0.5,1
			    ],
			    [-0.5,0.5,0.5,1
			    ]
			]
		    ]
		]
	    ]
	],"primitiveattributes",
	[
	]
    ],"primitives",
    [
	[
	    ["type","run","runtype","Poly","varyingfields",
		["vertex"
		],"uniformfields",
		{
		    "closed":true
		}
	    ],
	    [
		[
		    [0,1,2,3
		    ]
		],
		[
		    [4,5,6,7
		    ]
		],
		[
		    [8,9,10,11
		    ]
		],
		[
		    [12,13,14,15
		    ]
		],
		[
		    [16,17,18,19
		    ]
		],
		[
		    [20,21,22,23
		    ]
		]
	    ]
	]
    ],"pointgroups",
    [
    ],"primitivegroups",
    [
	[
	    ["name","faces","type","primitive"
	    ],
	    ["selection",
		["defaults",
		    ["size",1,"storage","int64","values",
			[0
			]
		    ],"unordered",
		    ["i8",
			[0,0,1,1,1,0
			]
		    ]
		]
	    ]
	]
    ]
]
