["fileversion","15.5.565","hasindex",false,"pointcount",8,"vertexcount",24,"primitivecount",6,"info",
    {
	"artist":"vangogh",
	"primcount_summary":"          6 Polygons\n",
	"hostname":"zundert",
	"bounds":[-0.5,0.5,-0.5,0.5,-0.5,0.5
	],
	"attribute_summary":"     1 vertex attributes:\tuv\n     1 point attributes:\tP\n     1 primitive attributes:\teven_odd\n",
	"date":"2016-09-29 14:04:09",
	"software":"Houdini 15.5.565"
    },"topology",
    ["pointref",
	["indices",
	    [1,5,4,0,2,6,5,1,3,7,6,2,0,4,7,3,2,1,0,3,5,6,7,4
	    ]
	]
    ],"attributes",
    ["vertexattributes",
	[
	    [
		["scope","public","type","numeric","name","uv","options",
		    {
		    }
		],
		["size",3,"storage","fpreal32","defaults",
		    ["size",0,"storage","int64","values",
			[
			]
		    ],"values",
		    ["size",3,"storage","fpreal32","tuples",
			[
			    [1,0,0
			    ],
			    [1,0,1
			    ],
			    [0,0,1
			    ],
			    [0,0,0
			    ],
			    [1,1,0
			    ],
			    [1,1,1
			    ],
			    [1,0,1
			    ],
			    [1,0,0
			    ],
			    [0,1,0
			    ],
			    [0,1,1
			    ],
			    [1,1,1
			    ],
			    [1,1,0
			    ],
			    [0,0,0
			    ],
			    [0,0,1
			    ],
			    [0,1,1
			    ],
			    [0,1,0
			    ],
			    [1,1,0
			    ],
			    [1,0,0
			    ],
			    [0,0,0
			    ],
			    [0,1,0
			    ],
			    [1,0,1
			    ],
			    [1,1,1
			    ],
			    [0,1,1
			    ],
			    [0,0,1
			    ]
			]
		    ]
		]
	    ]
	],"pointattributes",
	[
	    [
		["scope","public","type","numeric","name","P","options",
		    {
			"type":{
			    "type":"string",
			    "value":"point"
			}
		    }
		],
		["size",3,"storage","fpreal32","defaults",
		    ["size",3,"storage","fpreal64","values",
			[0,0,0
			]
		    ],"values",
		    ["size",3,"storage","fpreal32","tuples",
			[
			    [-0.5,-0.5,-0.5
			    ],
			    [0.5,-0.5,-0.5
			    ],
			    [0.5,-0.5,0.5
			    ],
			    [-0.5,-0.5,0.5
			    ],
			    [-0.5,0.5,-0.5
			    ],
			    [0.5,0.5,-0.5
			    ],
			    [0.5,0.5,0.5
			    ],
			    [-0.5,0.5,0.5
			    ]
			]
		    ]
		]
	    ]
	],"primitiveattributes",
	[
	    [
		["scope","public","type","string","name","even_odd","options",
		    {
		    }
		],
		["size",1,"storage","int32","strings",
		    ["piece0","piece1"
		    ],"indices",
		    ["size",1,"storage","int32","arrays",
			[
			    [0,1,0,1,0,1
			    ]
			]
		    ]
		]
	    ]
	]
    ],"primitives",
    [
	[
	    ["type","run","runtype","Poly","varyingfields",
		["vertex"
		],"uniformfields",
		{
		    "closed":true
		}
	    ],
	    [
		[
		    [0,1,2,3
		    ]
		],
		[
		    [4,5,6,7
		    ]
		],
		[
		    [8,9,10,11
		    ]
		],
		[
		    [12,13,14,15
		    ]
		],
		[
		    [16,17,18,19
		    ]
		],
		[
		    [20,21,22,23
		    ]
		]
	    ]
	]
    ]
]
