["fileversion","13.0.343","pointcount",4,"vertexcount",4,"primitivecount",1,"info",
    {
	"artist":"vangogh",
	"primcount_summary":"          1 Polygon\n",
	"hostname":"zundert",
	"bounds":[-0.5,0.5,0,0,-0.5,0.5
	],
	"attribute_summary":"     2 point attributes:\tuv, P\n",
	"date":"2014-08-19 12:21:45",
	"software":"Houdini 13.0.343"
    },"topology",
    ["pointref",
	["indices",
	    [0,1,3,2
	    ]
	]
    ],"attributes",
    ["vertexattributes",
	[
	],"pointattributes",
	[
	    [
		["scope","public","type","numeric","name","P","options",
		    {
			"type":{
			    "type":"string",
			    "value":"hpoint"
			}
		    }
		],
		["size",4,"storage","fpreal32","defaults",
		    ["size",4,"storage","fpreal64","values",
			[0,0,0,1
			]
		    ],"values",
		    ["size",4,"storage","fpreal32","tuples",
			[
			    [-0.5,0,-0.5,1
			    ],
			    [0.5,0,-0.5,1
			    ],
			    [-0.5,0,0.5,1
			    ],
			    [0.5,0,0.5,1
			    ]
			]
		    ]
		]
	    ],
	    [
		["scope","public","type","numeric","name","uv","options",
		    {
		    }
		],
		["size",3,"storage","fpreal32","defaults",
		    ["size",0,"storage","int64","values",
			[
			]
		    ],"values",
		    ["size",3,"storage","fpreal32","tuples",
			[
			    [0,0,0
			    ],
			    [1,0,0
			    ],
			    [0,1,0
			    ],
			    [1,1,0
			    ]
			]
		    ]
		]
	    ]
	]
    ],"primitives",
    [
	[
	    ["type","Poly"
	    ],
	    ["vertex",
		[0,1,2,3
		],"closed",true
	    ]
	]
    ]
]
