["fileversion","16.0.450","hasindex",false,"pointcount",4,"vertexcount",4,"primitivecount",1,"info",
    {
	"artist":"vangogh",
	"primcount_summary":"          1 Polygon\n",
	"hostname":"zundert",
	"bounds":[-0.5,0.5,0,0,-0.5,0.5
	],
	"attribute_summary":"     1 vertex attributes:\tuv\n     1 point attributes:\tP\n",
	"date":"2017-02-01 10:12:52",
	"software":"Houdini 16.0.450"
    },"topology",
    ["pointref",
	["indices",
	    [0,1,3,2
	    ]
	]
    ],"attributes",
    ["vertexattributes",
	[
	    [
		["scope","public","type","numeric","name","uv","options",
		    {
		    }
		],
		["size",3,"storage","fpreal32","defaults",
		    ["size",1,"storage","int64","values",
			[0
			]
		    ],"values",
		    ["size",3,"storage","fpreal32","tuples",
			[
			    [0,0,0
			    ],
			    [1,0,0
			    ],
			    [1,1,0
			    ],
			    [0,1,0
			    ]
			]
		    ]
		]
	    ]
	],"pointattributes",
	[
	    [
		["scope","public","type","numeric","name","P","options",
		    {
			"type":{
			    "type":"string",
			    "value":"point"
			}
		    }
		],
		["size",3,"storage","fpreal32","defaults",
		    ["size",1,"storage","fpreal64","values",
			[0
			]
		    ],"values",
		    ["size",3,"storage","fpreal32","tuples",
			[
			    [-0.5,0,-0.5
			    ],
			    [0.5,0,-0.5
			    ],
			    [-0.5,0,0.5
			    ],
			    [0.5,0,0.5
			    ]
			]
		    ]
		]
	    ]
	]
    ],"primitives",
    [
	[
	    ["type","Polygon_run"
	    ],
	    ["startvertex",0,"nprimitives",1,"nvertices",
		[4
		]
	    ]
	]
    ]
]
