["fileversion","16.0.450","hasindex",false,"pointcount",1,"vertexcount",1,"primitivecount",1,"info",
    {
	"artist":"vangogh",
	"primcount_summary":"          1 Packed Disk\n",
	"hostname":"zundert",
	"bounds":[0,2.90000010000000019,-0.359999954999999983,1.96000003999999994,-0.899999976000000035,0.899999976000000035
	],
	"attribute_summary":"     1 point attributes:\tP\n     1 primitive attributes:\tpath\n",
	"date":"2017-04-04 14:51:26",
	"software":"Houdini 16.0.450"
    },"topology",
    ["pointref",
	["indices",
	    [0
	    ]
	]
    ],"attributes",
    ["pointattributes",
	[
	    [
		["scope","public","type","numeric","name","P","options",
		    {
			"type":{
			    "type":"string",
			    "value":"point"
			}
		    }
		],
		["size",3,"storage","fpreal32","defaults",
		    ["size",1,"storage","fpreal64","values",
			[0
			]
		    ],"values",
		    ["size",3,"storage","fpreal32","tuples",
			[
			    [0,0,0
			    ]
			]
		    ]
		]
	    ]
	],"primitiveattributes",
	[
	    [
		["scope","public","type","string","name","path","options",
		    {
		    }
		],
		["size",1,"storage","int32","strings",
		    ["sphere.bgeo"
		    ],"indices",
		    ["size",1,"storage","int32","arrays",
			[
			    [0
			    ]
			]
		    ]
		]
	    ]
	]
    ],"primitives",
    [
	[
	    ["type","PackedDisk"
	    ],
	    ["parameters",
		{
		    "expandfilename":false,
		    "pointinstancetransform":false,
		    "expandframe":1,
		    "filename":"sphere.bgeo"
		},"pivot",
		[0,0,0
		],"transform",
		[1,0,0,0,1,0,0,0,1
		],"vertex",0,"viewportlod","full"
	    ]
	]
    ],"sharedprimitivedata",
    [
    ]
]
