["fileversion","16.5.268","hasindex",false,"pointcount",1,"vertexcount",1,"primitivecount",1,"info",
    {
	"artist":"vangogh",
	"primcount_summary":"          1 Packed Geometry\n",
	"hostname":"zundert",
	"bounds":[-1,1,-1,1,-1,1
	],
	"attribute_summary":"     1 point attributes:\tP\n     1 primitive attributes:\tpath\n",
	"date":"2017-11-15 14:43:24",
	"software":"Houdini 16.5.268"
    },"topology",
    ["pointref",
	["indices",
	    [0
	    ]
	]
    ],"attributes",
    ["pointattributes",
	[
	    [
		["scope","public","type","numeric","name","P","options",
		    {
			"type":{
			    "type":"string",
			    "value":"point"
			}
		    }
		],
		["size",3,"storage","fpreal32","defaults",
		    ["size",1,"storage","fpreal64","values",
			[0
			]
		    ],"values",
		    ["size",3,"storage","fpreal32","tuples",
			[
			    [0,0,0
			    ]
			]
		    ]
		]
	    ]
	],"primitiveattributes",
	[
	    [
		["scope","public","type","string","name","path","options",
		    {
		    }
		],
		["size",1,"storage","int32","strings",
		    ["op:/obj/packed/pack1"
		    ],"indices",
		    ["size",1,"storage","int32","arrays",
			[
			    [0
			    ]
			]
		    ]
		]
	    ]
	]
    ],"primitives",
    [
	[
	    ["type","PackedGeometry"
	    ],
	    ["parameters",
		{
		    "pointinstancetransform":false,
		    "cachedbounds":[-1,1,-1,1,-1,1
		    ],
		    "embedded":"embed:0x7f9d382f0f00"
		},"pivot",
		[0,0,0
		],"transform",
		[1,0,0,0,1,0,0,0,1
		],"vertex",0,"viewportlod","full"
	    ]
	]
    ],"sharedprimitivedata",
    ["PackedGeometry",
	["gu:embeddedgeo","embed:0x7f9d382f0f00",
	    ["fileversion","16.5.268","hasindex",false,"pointcount",1,"vertexcount",1,"primitivecount",1,"info",
		{
		    "artist":"vangogh",
		    "primcount_summary":"          1 Sphere\n",
		    "hostname":"zundert",
		    "bounds":[-1,1,-1,1,-1,1
		    ],
		    "attribute_summary":"     1 point attributes:\tP\n",
		    "date":"2017-11-15 14:43:24",
		    "software":"Houdini 16.5.268"
		},"topology",
		["pointref",
		    ["indices",
			[0
			]
		    ]
		],"attributes",
		["pointattributes",
		    [
			[
			    ["scope","public","type","numeric","name","P","options",
				{
				    "type":{
					"type":"string",
					"value":"point"
				    }
				}
			    ],
			    ["size",3,"storage","fpreal32","defaults",
				["size",1,"storage","fpreal64","values",
				    [0
				    ]
				],"values",
				["size",3,"storage","fpreal32","tuples",
				    [
					[0,0,0
					]
				    ]
				]
			    ]
			]
		    ]
		],"primitives",
		[
		    [
			["type","Sphere"
			],
			["vertex",0,"transform",
			    [1,0,0,0,0,-1,0,1,0
			    ]
			]
		    ]
		]
	    ]
	]
    ]
]
