["fileversion","16.5.268","hasindex",false,"pointcount",4,"vertexcount",4,"primitivecount",4,"info",
    {
	"artist":"vangogh",
	"primcount_summary":"          4 Packed Geometries\n",
	"hostname":"zundert",
	"bounds":[-1,10,-1,1,-1,1
	],
	"attribute_summary":"     1 point attributes:\tP\n",
	"date":"2017-11-15 14:44:03",
	"software":"Houdini 16.5.268"
    },"topology",
    ["pointref",
	["indices",
	    [0,1,2,3
	    ]
	]
    ],"attributes",
    ["pointattributes",
	[
	    [
		["scope","public","type","numeric","name","P","options",
		    {
			"type":{
			    "type":"string",
			    "value":"point"
			}
		    }
		],
		["size",3,"storage","fpreal32","defaults",
		    ["size",1,"storage","fpreal64","values",
			[0
			]
		    ],"values",
		    ["size",3,"storage","fpreal32","tuples",
			[
			    [0,0,0
			    ],
			    [3,0,0
			    ],
			    [6,0,0
			    ],
			    [9,0,0
			    ]
			]
		    ]
		]
	    ]
	]
    ],"primitives",
    [
	[
	    ["type","run","runtype","PackedGeometry","varyingfields",
		["parameters","vertex"
		],"uniformfields",
		{
		    "viewportlod":"full",
		    "pivot":[0,0,0
		    ],
		    "transform":[1,0,0,0,1,0,0,0,1
		    ]
		}
	    ],
	    [
		[
		    {
			"pointinstancetransform":false,
			"cachedbounds":[-1,1,-1,1,-1,1
			],
			"embedded":"embed:0x7f31fdef0f00"
		    },0
		],
		[
		    {
			"pointinstancetransform":false,
			"cachedbounds":[-1,1,-1,1,-1,1
			],
			"embedded":"embed:0x7f31fdef0f00"
		    },1
		],
		[
		    {
			"pointinstancetransform":false,
			"cachedbounds":[-1,1,-1,1,-1,1
			],
			"embedded":"embed:0x7f31fdef0f00"
		    },2
		],
		[
		    {
			"pointinstancetransform":false,
			"cachedbounds":[-1,1,-1,1,-1,1
			],
			"embedded":"embed:0x7f31fdef0f00"
		    },3
		]
	    ]
	]
    ],"sharedprimitivedata",
    ["PackedGeometry",
	["gu:embeddedgeo","embed:0x7f31fdef0f00",
	    ["fileversion","16.5.268","hasindex",false,"pointcount",1,"vertexcount",1,"primitivecount",1,"info",
		{
		    "artist":"vangogh",
		    "primcount_summary":"          1 Sphere\n",
		    "hostname":"zundert",
		    "bounds":[-1,1,-1,1,-1,1
		    ],
		    "attribute_summary":"     1 point attributes:\tP\n",
		    "date":"2017-11-15 14:44:03",
		    "software":"Houdini 16.5.268"
		},"topology",
		["pointref",
		    ["indices",
			[0
			]
		    ]
		],"attributes",
		["pointattributes",
		    [
			[
			    ["scope","public","type","numeric","name","P","options",
				{
				    "type":{
					"type":"string",
					"value":"point"
				    }
				}
			    ],
			    ["size",3,"storage","fpreal32","defaults",
				["size",1,"storage","fpreal64","values",
				    [0
				    ]
				],"values",
				["size",3,"storage","fpreal32","tuples",
				    [
					[0,0,0
					]
				    ]
				]
			    ]
			]
		    ]
		],"primitives",
		[
		    [
			["type","Sphere"
			],
			["vertex",0,"transform",
			    [1,0,0,0,0,-1,0,1,0
			    ]
			]
		    ]
		]
	    ]
	]
    ]
]
