["fileversion","15.0.244.16","hasindex",false,"pointcount",3,"vertexcount",3,"primitivecount",3,"info",
    {
	"artist":"vangogh",
	"primcount_summary":"          3 Packed Geometries\n",
	"hostname":"zundert",
	"bounds":[-1,7,-1,1,-1,1
	],
	"attribute_summary":"     1 point attributes:\tP\n",
	"date":"2016-01-15 14:52:02",
	"software":"Houdini 15.0.244.16"
    },"topology",
    ["pointref",
	["indices",
	    [0,1,2
	    ]
	]
    ],"attributes",
    ["pointattributes",
	[
	    [
		["scope","public","type","numeric","name","P","options",
		    {
			"type":{
			    "type":"string",
			    "value":"point"
			}
		    }
		],
		["size",3,"storage","fpreal32","defaults",
		    ["size",3,"storage","fpreal64","values",
			[0,0,0
			]
		    ],"values",
		    ["size",3,"storage","fpreal32","tuples",
			[
			    [0,0,0
			    ],
			    [3,0,0
			    ],
			    [6,0,0
			    ]
			]
		    ]
		]
	    ]
	]
    ],"primitives",
    [
	[
	    ["type","PackedGeometry"
	    ],
	    ["parameters",
		{
		    "pointinstancetransform":false,
		    "cachedbounds":[-1,1,-1,1,-1,1
		    ],
		    "embedded":"embed:0x7f5c3bfe6400"
		},"pivot",
		[0,0,0
		],"transform",
		[1,0,0,0,1,0,0,0,1
		],"vertex",0,"viewportlod","full"
	    ]
	],
	[
	    ["type","PackedGeometry"
	    ],
	    ["parameters",
		{
		    "pointinstancetransform":false,
		    "cachedbounds":[-1,1,-1,1,-1,1
		    ],
		    "embedded":"embed:0x7f5c3bfe6400"
		},"pivot",
		[0,0,0
		],"transform",
		[1,0,0,0,1,0,0,0,1
		],"vertex",1,"viewportlod","full"
	    ]
	],
	[
	    ["type","PackedGeometry"
	    ],
	    ["parameters",
		{
		    "pointinstancetransform":false,
		    "cachedbounds":[-1,1,-1,1,-1,1
		    ],
		    "embedded":"embed:0x7f5c3bfe6400"
		},"pivot",
		[0,0,0
		],"transform",
		[1,0,0,0,1,0,0,0,1
		],"vertex",2,"viewportlod","full"
	    ]
	]
    ],"sharedprimitivedata",
    ["PackedGeometry",
	["gu:embeddedgeo","embed:0x7f5c3bfe6400",
	    ["fileversion","15.0.244.16","hasindex",false,"pointcount",1,"vertexcount",1,"primitivecount",1,"info",
		{
		    "artist":"vangogh",
		    "primcount_summary":"          1 Sphere\n",
		    "hostname":"zundert",
		    "bounds":[-1,1,-1,1,-1,1
		    ],
		    "attribute_summary":"     1 point attributes:\tP\n",
		    "date":"2016-01-15 14:52:02",
		    "software":"Houdini 15.0.244.16"
		},"topology",
		["pointref",
		    ["indices",
			[0
			]
		    ]
		],"attributes",
		["pointattributes",
		    [
			[
			    ["scope","public","type","numeric","name","P","options",
				{
				    "type":{
					"type":"string",
					"value":"point"
				    }
				}
			    ],
			    ["size",3,"storage","fpreal32","defaults",
				["size",3,"storage","fpreal64","values",
				    [0,0,0
				    ]
				],"values",
				["size",3,"storage","fpreal32","tuples",
				    [
					[0,0,0
					]
				    ]
				]
			    ]
			]
		    ]
		],"primitives",
		[
		    [
			["type","Sphere"
			],
			["vertex",0,"transform",
			    [1,0,0,0,0,-1,0,1,0
			    ]
			]
		    ]
		]
	    ]
	]
    ]
]
